AWSTemplateFormatVersion: 2010-09-09
Resources:
  ChangeIsSimpleApp:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: mlchangeissimpleapp
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ChangeIsSimpleApp
                - /*
      Bucket: !Ref ChangeIsSimpleApp
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - ChangeIsSimpleApp
      - WebsiteURL
    Description: URL for website hosted on S3
  ChangeIsSimpleAppSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - ChangeIsSimpleApp
          - DomainName
    Description: Name of S3 bucket to hold website content